CREATE OR REPLACE PROCEDURE UTILS.SP_LOAD_SILVER_DIM_PASSENGER()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO SILVER.DIM_PASSENGER AS T
    USING (
        SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY 
        FROM BRONZE.RAW_AIRLINE_DATA
    ) AS S
    ON T.PASSENGER_ID = S.PASSENGER_ID
    WHEN MATCHED THEN UPDATE SET
        T.FIRST_NAME = S.FIRST_NAME,
        T.LAST_NAME = S.LAST_NAME,
        T.GENDER = S.GENDER,
        T.AGE = S.AGE,
        T.NATIONALITY = S.NATIONALITY,
        T.UPDATE_TIMESTAMP = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP
    ) VALUES (
        S.PASSENGER_ID, S.FIRST_NAME, S.LAST_NAME, S.GENDER, S.AGE, S.NATIONALITY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    );

    INSERT INTO UTILS.AUDIT_LOG (TASK_NAME, STATUS, TARGET_TABLE, AFFECTED_ROWS)
    SELECT 'LOAD_SILVER_PASSENGER', 'SUCCESS', 'DIM_PASSENGER', COUNT(*) 
    FROM SILVER.DIM_PASSENGER 
    WHERE UPDATE_TIMESTAMP >= DATEADD(minute, -5, CURRENT_TIMESTAMP());

    COMMIT;
    RETURN 'Success';
END;
$$;