CREATE OR REPLACE PROCEDURE UTILS.SP_LOAD_SILVER_DIM_AIRPORT()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO SILVER.DIM_AIRPORT AS T
    USING (
        SELECT 
            AIRPORT_NAME,
            MAX(AIRPORT_COUNTRY_CODE) as AIRPORT_COUNTRY_CODE,
            MAX(COUNTRY_NAME) as COUNTRY_NAME,
            MAX(AIRPORT_CONTINENT) as AIRPORT_CONTINENT
        FROM BRONZE.RAW_AIRLINE_DATA 
        WHERE AIRPORT_NAME IS NOT NULL
        GROUP BY AIRPORT_NAME 
    ) AS S
    ON T.AIRPORT_NAME = S.AIRPORT_NAME
    
    WHEN MATCHED THEN UPDATE SET
        T.COUNTRY_CODE = S.AIRPORT_COUNTRY_CODE,
        T.COUNTRY_NAME = S.COUNTRY_NAME,
        T.CONTINENT = S.AIRPORT_CONTINENT,
        T.UPDATE_TIMESTAMP = CURRENT_TIMESTAMP()
        
    WHEN NOT MATCHED THEN INSERT (
        AIRPORT_NAME, COUNTRY_CODE, COUNTRY_NAME, CONTINENT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP
    ) VALUES (
        S.AIRPORT_NAME, S.AIRPORT_COUNTRY_CODE, S.COUNTRY_NAME, S.AIRPORT_CONTINENT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    );

    INSERT INTO UTILS.AUDIT_LOG (TASK_NAME, STATUS, TARGET_TABLE, AFFECTED_ROWS)
    SELECT 'LOAD_SILVER_AIRPORT', 'SUCCESS', 'DIM_AIRPORT', COUNT(*) 
    FROM SILVER.DIM_AIRPORT 
    WHERE UPDATE_TIMESTAMP >= DATEADD(minute, -5, CURRENT_TIMESTAMP());
    
    COMMIT;
    RETURN 'Success';
END;
$$;