CREATE OR REPLACE PROCEDURE UTILS.SP_LOAD_SILVER_FACT_FLIGHT()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT INTO SILVER.FACT_FLIGHT (
        PASSENGER_KEY,
        AIRPORT_KEY,
        DEPARTURE_DATE,
        ARRIVAL_AIRPORT_CODE,
        PILOT_NAME,
        FLIGHT_STATUS,
        TICKET_TYPE,
        PASSENGER_STATUS,
        CREATE_TIMESTAMP
    )
    SELECT 
        P.PASSENGER_KEY,
        A.AIRPORT_KEY,
        TRY_TO_DATE(B.DEPARTURE_DATE, 'MM/DD/YYYY'), 
        B.ARRIVAL_AIRPORT,
        B.PILOT_NAME,
        B.FLIGHT_STATUS,
        B.TICKET_TYPE,
        B.PASSENGER_STATUS,
        CURRENT_TIMESTAMP()
    FROM BRONZE.RAW_AIRLINE_DATA B
    LEFT JOIN SILVER.DIM_PASSENGER P 
        ON B.PASSENGER_ID = P.PASSENGER_ID
    LEFT JOIN SILVER.DIM_AIRPORT A 
        ON B.AIRPORT_NAME = A.AIRPORT_NAME;

    INSERT INTO UTILS.AUDIT_LOG (TASK_NAME, STATUS, TARGET_TABLE, AFFECTED_ROWS)
    SELECT 'LOAD_SILVER_FACT', 'SUCCESS', 'FACT_FLIGHT', COUNT(*) 
    FROM SILVER.FACT_FLIGHT 
    WHERE CREATE_TIMESTAMP >= DATEADD(minute, -5, CURRENT_TIMESTAMP());

    COMMIT;
    RETURN 'Success';
END;
$$;