CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
USE DATABASE AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS UTILS; 

CREATE OR REPLACE TABLE UTILS.AUDIT_LOG (
    TASK_NAME VARCHAR,
    STATUS VARCHAR,
    TARGET_TABLE VARCHAR,
    AFFECTED_ROWS INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() 
);

CREATE OR REPLACE TABLE BRONZE.RAW_AIRLINE_DATA (
    ROW_ID INT,                         
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE VARCHAR,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.DIM_PASSENGER (
    PASSENGER_KEY INT IDENTITY(1,1),
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,                         
    NATIONALITY VARCHAR,
    CREATE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.DIM_AIRPORT (
    AIRPORT_KEY INT IDENTITY(1,1),
    AIRPORT_NAME VARCHAR,
    COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR,
    CREATE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.FACT_FLIGHT (
    FLIGHT_ID INT IDENTITY(1,1),
    PASSENGER_KEY INT,
    AIRPORT_KEY INT,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT_CODE VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR,
    CREATE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AIRLINE_DWH.GOLD.FLIGHT_ANALYTICS (
    DEPARTURE_DATE DATE,
    COUNTRY_NAME VARCHAR,
    AIRPORT_NAME VARCHAR,
    TOTAL_FLIGHTS INT,
    TOTAL_PASSENGERS INT,
    DELAYED_FLIGHTS INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE FILE FORMAT UTILS.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE UTILS.RAW_STAGE
    FILE_FORMAT = UTILS.CSV_FORMAT;

CREATE OR REPLACE STREAM BRONZE.RAW_AIRLINE_STREAM ON TABLE BRONZE.RAW_AIRLINE_DATA;