USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE FILE FORMAT UTILS.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE UTILS.RAW_STAGE
    FILE_FORMAT = UTILS.CSV_FORMAT;

CREATE OR REPLACE STREAM BRONZE.RAW_AIRLINE_STREAM 
ON TABLE BRONZE.RAW_AIRLINE_DATA;