CREATE OR REPLACE PROCEDURE UTILS.SP_LOAD_GOLD_AGGREGATES() 
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    TRUNCATE TABLE GOLD.FLIGHT_ANALYTICS;
    INSERT INTO GOLD.FLIGHT_ANALYTICS (
        DEPARTURE_DATE,
        COUNTRY_NAME,
        AIRPORT_NAME,
        TOTAL_FLIGHTS,
        TOTAL_PASSENGERS,
        DELAYED_FLIGHTS,
        LOAD_TIMESTAMP
    )
    SELECT 
        F.DEPARTURE_DATE,
        A.COUNTRY_NAME,
        A.AIRPORT_NAME,
        COUNT(F.FLIGHT_ID) AS TOTAL_FLIGHTS,
        COUNT(DISTINCT F.PASSENGER_KEY) AS TOTAL_PASSENGERS,
        SUM(CASE WHEN F.FLIGHT_STATUS = 'Delayed' THEN 1 ELSE 0 END) AS DELAYED_FLIGHTS,
        CURRENT_TIMESTAMP()
    FROM SILVER.FACT_FLIGHT F
    JOIN SILVER.DIM_AIRPORT A ON F.AIRPORT_KEY = A.AIRPORT_KEY
    GROUP BY 1, 2, 3;

    INSERT INTO UTILS.AUDIT_LOG (TASK_NAME, STATUS, TARGET_TABLE, AFFECTED_ROWS)
    SELECT 'LOAD_GOLD', 'SUCCESS', 'FLIGHT_ANALYTICS', COUNT(*) 
    FROM GOLD.FLIGHT_ANALYTICS 
    WHERE LOAD_TIMESTAMP >= DATEADD(minute, -5, CURRENT_TIMESTAMP());

    COMMIT;
    
    RETURN 'Success';
END;
$$;