USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE TABLE UTILS.ACCESS_CONTROL (
    USER_ROLE VARCHAR,
    ALLOWED_COUNTRY VARCHAR
);

INSERT INTO UTILS.ACCESS_CONTROL (USER_ROLE, ALLOWED_COUNTRY) VALUES 
('CHINESE_ANALYST', 'China'),
('USA_ANALYST', 'United States');

CREATE OR REPLACE ROW ACCESS POLICY UTILS.COUNTRY_POLICY 
AS (COUNTRY_VAL VARCHAR) RETURNS BOOLEAN ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN TRUE
    ELSE EXISTS (
        SELECT 1 FROM UTILS.ACCESS_CONTROL A
        WHERE A.USER_ROLE = CURRENT_ROLE() 
          AND A.ALLOWED_COUNTRY = COUNTRY_VAL
    )
    END;

ALTER TABLE GOLD.FLIGHT_ANALYTICS 
ADD ROW ACCESS POLICY UTILS.COUNTRY_POLICY ON (COUNTRY_NAME);
