CREATE OR REPLACE TABLE UTILS.ACCESS_CONTROL (
    USER_ROLE VARCHAR,
    ALLOWED_COUNTRY VARCHAR
);
INSERT INTO UTILS.ACCESS_CONTROL VALUES ('CHINESE_ANALYST', 'China');

CREATE OR REPLACE SECURE VIEW GOLD.VW_PASSENGERS_SECURE AS
SELECT * FROM SILVER.DIM_PASSENGER P
WHERE EXISTS (
    SELECT 1 FROM UTILS.ACCESS_CONTROL A
    WHERE A.USER_ROLE = CURRENT_ROLE()  
    AND A.ALLOWED_COUNTRY = P.NATIONALITY
);